### PR TITLE
SIAM CSE 2017 minisymposium Schunert

### PR DESCRIPTION
**Pull request by snschune**

### CODE REVIEW

**Comment by jwpeterson** [comment]
Thanks but I think we only need the .pptx.  The PDF can be generated from that correct?

**Comment by roystgnr** [comment]
Great; thanks!

**Comment by roystgnr** [comment]
Let me make sure the pptx opens fine in LibreOffice.

**Comment by roystgnr** [comment]
Huh.  LibreOffice seems to think that the phrase "2nd order/ 1st sweep" is in bold.  This causes it to word wrap, which then blocks out a bit of the title on the image below.

Same "last line in bold" bug on other tables too, I'd just never have noticed it if it wasn't for the occlusion case.

Meh, close enough; we can remove the PDF.

**Comment by jwpeterson** [comment]
> Meh, close enough; we can remove the PDF.

I'll grab it directly from this branch and merge it by hand, then close this PR.

**Comment by jwpeterson** [comment]
PPT added in dd62df4.

**Pull request closed without merging**
